import React from "react";

const Header = ({ course }) => <h2>{course}</h2>;

const Total = ({ sum }) => (
  <p>
    <strong>total of {sum} exercises</strong>
  </p>
);

const Part = ({ part }) => (
  <p>
    {part.name} {part.exercises}
  </p>
);
const Course = ({ course, total }) => (
  <div>
    <Header course={course.name} />
    <Content parts={course.parts} />
    <Total sum={total} />
  </div>
);

const CourseList = ({ course }) => {
  /// return is necessary
  return (
    <div>
      {course.map((singleCourse, i) => {
        console.log(singleCourse.name);
        return (
          // list items, i.e. the elements generated by the map method, must each have a unique key value
          <div key={i}>
            <Course
              course={singleCourse}
              total={singleCourse.parts.reduce(
                (previousValue, currentObject) =>
                  previousValue + currentObject.exercises,
                0
              )}
            />
          </div>
        );
      })}
    </div>
  );
};

const Content = ({ parts }) => (
  <div>
    {parts.map((part, i) => {
      return <Part key={i} part={part} />;
    })}
  </div>
);

const App = () => {
  const course = [
    {
      id: 1,
      name: "Half Stack application development",
      parts: [
        {
          name: "Fundamentals of React",
          exercises: 10,
          id: 1,
        },
        {
          name: "Using props to pass data",
          exercises: 7,
          id: 2,
        },
        {
          name: "State of a component",
          exercises: 14,
          id: 3,
        },
        {
          name: "Redux",
          exercises: 11,
          id: 4,
        },
      ],
    },

    {
      name: "Node.js",
      id: 2,
      parts: [
        {
          name: "Routing",
          exercises: 3,
          id: 1,
        },
        {
          name: "Middlewares",
          exercises: 7,
          id: 2,
        },
      ],
    },
  ];

  return (
    <div>
      <h1>Web Development Curriculum</h1>
      <CourseList course={course} />
    </div>
  );
};

export default App;
